cc_library(
    name = "reductions_sorted",
    hdrs = [
        "driver.h",
        "foldings.h",
        "prune.h",
        "removals.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//ds:bmatching_lib",
        "//ds:indexed_priority_queue",
        "//ds:modifiable_hypergraph_lib",
        "//utils:random_lib",
        "//utils:range_lib",
        "@easyloggingpp",
    ],
)
