cc_library(
    name = "random_lib",
    hdrs = ["random.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "range_lib",
    hdrs = ["range.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "systeminfo",
    srcs = ["systeminfo.cc"],
    hdrs = ["systeminfo.h"],
    visibility = ["//visibility:public"],
)
