cc_library(
    name = "ils",
    hdrs = [
        "ils.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//ds:bmatching_lib",
        "//ds:indexed_priority_queue",
        "//ds:modifiable_hypergraph_lib",
        "//utils:random_lib",
        "//utils:range_lib",
        "@com_google_absl//absl/container:flat_hash_map",
    ],
)
