cc_library(
    name = "greedy",
    hdrs = ["ordered.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//ds:bmatching_lib",
        "//ds:indexed_priority_queue",
        "//ds:modifiable_hypergraph_lib",
        "//utils:random_lib",
        "//utils:range_lib",
    ],
)
