cc_binary(
    name = "binary_to_textproto",
    srcs = ["binary_to_textproto.cc"],
    deps = [
        "//app:app_io_cc_proto",
        "//runner:hypergraph_storage_system",
        "@com_google_absl//absl/strings",
    ],
)
